INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0134', 'Emily Johnson');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0145', 'Michael Smith');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0156', 'Jacob Brown');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0167', 'Madison Davis');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0178', 'Olivia Martinez');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0189', 'Daniel Wilson');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0190', 'Sophia Anderson');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0101', 'Ethan Thomas');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0102', 'Ava Moore');

INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0113', 'Liam Johnson');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0114', 'Emma Smith');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0115', 'Noah Williams');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0116', 'Isabella Brown');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0117', 'James Jones');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0118', 'Mia Garcia');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0119', 'Benjamin Miller');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0120', 'Charlotte Davis');

INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0121', 'Elijah Rodriguez');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0122', 'Amelia Martinez');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0123', 'Alexander Hernandez');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0124', 'Harper Lopez');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0125', 'William Gonzalez');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0126', 'Evelyn Wilson');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0127', 'Daniel Anderson');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0128', 'Abigail Thomas');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0129', 'Matthew Taylor');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0130', 'Elizabeth Moore');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0131', 'Joseph Jackson');
INSERT INTO TBL_PERSON (PHONE, NAME) VALUES ('(202) 555-0132', 'Sofia White');

INSERT INTO TBL_CLIENT (DATE_OF_BIRTH, PERSON_ID) VALUES (DATE '2000-08-02', 1);
INSERT INTO TBL_CLIENT (DATE_OF_BIRTH, PERSON_ID) VALUES (DATE '1998-01-21', 2);
INSERT INTO TBL_CLIENT (DATE_OF_BIRTH, PERSON_ID) VALUES (DATE '1995-01-11', 3);
INSERT INTO TBL_CLIENT (DATE_OF_BIRTH, PERSON_ID) VALUES (DATE '1999-02-13', 10);
INSERT INTO TBL_CLIENT (DATE_OF_BIRTH, PERSON_ID) VALUES (DATE '1990-07-07', 11);
INSERT INTO TBL_CLIENT (DATE_OF_BIRTH, PERSON_ID) VALUES (DATE '1979-03-09', 12);
INSERT INTO TBL_CLIENT (DATE_OF_BIRTH, PERSON_ID) VALUES (DATE '1956-11-15', 13);
INSERT INTO TBL_CLIENT (DATE_OF_BIRTH, PERSON_ID) VALUES (DATE '1989-03-26', 14);
INSERT INTO TBL_CLIENT (DATE_OF_BIRTH, PERSON_ID) VALUES (DATE '1991-08-12', 15);
INSERT INTO TBL_CLIENT (DATE_OF_BIRTH, PERSON_ID) VALUES (DATE '1992-06-28', 16);
INSERT INTO TBL_CLIENT (DATE_OF_BIRTH, PERSON_ID) VALUES (DATE '1996-06-10', 17);

INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (TRUE, 4);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (TRUE, 5);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (FALSE, 6);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (TRUE, 18);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (TRUE, 19);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (TRUE, 20);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (TRUE, 21);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (FALSE, 22);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (TRUE, 23);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (FALSE, 24);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (TRUE, 25);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (FALSE, 26);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (FALSE, 27);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (TRUE, 28);
INSERT INTO TBL_PROFESSIONAL (ACTIVE, PERSON_ID) VALUES (TRUE, 29);

INSERT INTO TBL_USER (EMAIL, PASSWORD, PERSON_ID) VALUES ('sophia@gmail.com', '123456', 7);
INSERT INTO TBL_USER (EMAIL, PASSWORD, PERSON_ID) VALUES ('ethan@gmail.com', '123456', 8);
INSERT INTO TBL_USER (EMAIL, PASSWORD, PERSON_ID) VALUES ('ava@gmail.com', '123456', 9);

INSERT INTO TBL_ROLE (ROLE) VALUES ('ROLE_ADMIN');
INSERT INTO TBL_ROLE (ROLE) VALUES ('ROLE_OPERATOR');

INSERT INTO TBL_USER_ROLE (ROLE_ID, USER_ID) VALUES (1, 7);
INSERT INTO TBL_USER_ROLE (ROLE_ID, USER_ID) VALUES (2, 7);
INSERT INTO TBL_USER_ROLE (ROLE_ID, USER_ID) VALUES (2, 8);
INSERT INTO TBL_USER_ROLE (ROLE_ID, USER_ID) VALUES (2, 9);

INSERT INTO TBL_AREA (NAME) VALUES ('Physiotherapy');
INSERT INTO TBL_AREA (NAME) VALUES ('Occupational Therapy');
INSERT INTO TBL_AREA (NAME) VALUES ('Medical Clinic');
INSERT INTO TBL_AREA (NAME) VALUES ('Psychology');
INSERT INTO TBL_AREA (NAME) VALUES ('Nutrition');

INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (1,4);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (1,5);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (2,5);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (2,6);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (3,6);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (3,4);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (1,18);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (2,19);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (3,20);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (4,21);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (5,22);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (1,23);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (2,24);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (3,25);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (4,26);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (5,27);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (1,28);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (2,29);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (2,4);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (4,5);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (5,6);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (3,18);
INSERT INTO TBL_AREA_PROFESSIONAL (AREA_ID, PROFESSIONAL_ID) VALUES (5,19);

INSERT INTO TBL_APPOINTMENT_TYPE (TYPE) VALUES ('Private');
INSERT INTO TBL_APPOINTMENT_TYPE (TYPE) VALUES ('Municipal Agreement');
INSERT INTO TBL_APPOINTMENT_TYPE (TYPE) VALUES ('Blue Plan Agreement');

-- SUNDAY=1, MONDAY=2, ... SATURDAY=7
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (2, '08:00:00-03', '10:00:00-03', 4, 30, 4);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (3, '08:00:00-03', '12:00:00-03', 8, 30, 4);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (3, '14:00:00-03', '18:00:00-03', 8, 30, 4);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (6, '14:00:00-03', '18:00:00-03', 8, 30, 4);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (2, '08:00:00-03', '12:00:00-03', 8, 30, 5);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (2, '14:00:00-03', '18:00:00-03', 8, 30, 5);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (3, '14:00:00-03', '18:00:00-03', 8, 30, 5);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (2, '09:00:00-03', '12:00:00-03', 6, 30, 18);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (3, '08:00:00-03', '11:00:00-03', 6, 30, 19);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (4, '13:00:00-03', '17:00:00-03', 8, 30, 20);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (5, '08:00:00-03', '12:00:00-03', 8, 30, 21);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (2, '14:00:00-03', '18:00:00-03', 8, 30, 22);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (3, '09:00:00-03', '13:00:00-03', 8, 30, 23);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (4, '08:00:00-03', '11:00:00-03', 6, 30, 24);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (5, '13:00:00-03', '17:00:00-03', 8, 30, 25);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (2, '10:00:00-03', '14:00:00-03', 8, 30, 26);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (3, '08:00:00-03', '12:00:00-03', 8, 30, 27);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (4, '09:00:00-03', '13:00:00-03', 8, 30, 28);
INSERT INTO TBL_WORK_SCHEDULE_ITEM (DAY_OF_WEEK, START_TIME, END_TIME, SLOTS, SLOT_SIZE, PROFESSIONAL_ID) VALUES (5, '14:00:00-03', '18:00:00-03', 8, 30, 29);

INSERT INTO TBL_APPOINTMENT (DATE, START_TIME, END_TIME, STATUS, COMMENTS, CLIENT_ID, PROFESSIONAL_ID, AREA_ID, APPOINTMENT_TYPE_ID) VALUES ('2026-04-06 00:00:00-03', '08:00:00-03', '08:30:00-03', 'OPEN', '3 installments', 2, 4, 1, 1);
INSERT INTO TBL_APPOINTMENT (DATE, START_TIME, END_TIME, STATUS, COMMENTS, CLIENT_ID, PROFESSIONAL_ID, AREA_ID, APPOINTMENT_TYPE_ID) VALUES ('2026-04-06 00:00:00-03', '08:30:00-03', '09:00:00-03', 'OPEN', '3 installments', 1, 4, 1, 1);
INSERT INTO TBL_APPOINTMENT (DATE, START_TIME, END_TIME, STATUS, COMMENTS, CLIENT_ID, PROFESSIONAL_ID, AREA_ID, APPOINTMENT_TYPE_ID) VALUES ('2026-04-06 00:00:00-03', '09:00:00-03', '09:30:00-03', 'OPEN', '3 installments', 1, 4, 1, 1);
INSERT INTO TBL_APPOINTMENT (DATE, START_TIME, END_TIME, STATUS, COMMENTS, CLIENT_ID, PROFESSIONAL_ID, AREA_ID, APPOINTMENT_TYPE_ID) VALUES ('2026-04-06 00:00:00-03', '09:30:00-03', '10:00:00-03', 'OPEN', '', 2, 4, 1, 2);
INSERT INTO TBL_APPOINTMENT (DATE, START_TIME, END_TIME, STATUS, COMMENTS, CLIENT_ID, PROFESSIONAL_ID, AREA_ID, APPOINTMENT_TYPE_ID) VALUES ('2026-04-13 00:00:00-03', '09:30:00-03', '10:00:00-03', 'OPEN', 'Call before appointment', 3, 4, 3, 3);